import org.apache.tools.ant.filters.ReplaceTokens
import work.lclpnet.build.task.GithubDeploymentTask

plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
}

Properties props = buildUtils.loadProperties('publish.properties')

group = project.maven_group
version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

repositories {
    mavenCentral()

    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }
}

configurations {
    provide {
        transitive = false
    }
}

dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    def includeImpl = { dep ->
        include(dep)
        implementation(dep)
    }

    implementation(libs.kibu)

    implementation(libs.json)
    compileOnly(libs.jetbrains.annotations)

    includeImpl(libs.json.config4j)
    includeImpl(libs.lclpnetwork.api)
    includeImpl(libs.lclpstorage)
    implementation(libs.translations4j)

    compileOnly(variantOf(libs.translations4j) { classifier('network') })
    localRuntime(variantOf(libs.translations4j) { classifier('network') })
    include(variantOf(libs.translations4j) { classifier('network') })

    compileOnly(libs.mcserver.api.base)
    localRuntime(libs.mcserver.api.base)
    provide(libs.mcserver.api.base)

    // test dependencies
    testImplementation(libs.fabric.loader.junit)
}

loom {
    serverOnlyMinecraftJar()

    runs {
        remove client
    }
}

test {
    useJUnitPlatform()
    systemProperty('fabric.side', 'server')
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(javaVersion)
}

processResources {
    def tokens = [
            "version": project.version.toString(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": javaVersion.toString()
    ]

    inputs.properties(tokens)

    filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

jar {
    from configurations.provide.collect {
        zipTree(it)
    }
}

[jar, sourcesJar].each {
    it.from("LICENSE.md") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] $project.name $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

publishing {
    buildUtils.setupPublishRepository(repositories, props)

    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'MCServer Fabric Implementation'
                description = 'A Java library to manage Minecraft server backend interaction with LCLPNetwork. For Fabric.'
            }
        }
    }
}